# Prometheus configuration for Enhanced Telecom AI System
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Main API Server
  - job_name: 'telecom-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # AI Agents
  - job_name: 'qos-anomaly-agent'
    static_configs:
      - targets: ['qos-agent:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'failure-prediction-agent'
    static_configs:
      - targets: ['failure-agent:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'traffic-forecast-agent'
    static_configs:
      - targets: ['traffic-agent:8003']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'energy-optimization-agent'
    static_configs:
      - targets: ['energy-agent:8004']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'security-detection-agent'
    static_configs:
      - targets: ['security-agent:8005']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'data-quality-agent'
    static_configs:
      - targets: ['quality-agent:8006']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Database
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
